#include "korganizerutil.h"

// autogenerated dbus interfaces
#include "calendar_interface.h"
#include "korganizer_interface.h"

// qt headers
#include <QDBusConnection>
#include <QDBusInterface>
#include <QDBusReply>

// kde headers
#include <KLocale>
#include <KToolInvocation>
#include <KWindowSystem>


void KOrganizerUtil::showMainWindow()
{
    QDBusInterface kontactInterface("org.kde.korganizer",
                                    "/kontact/MainWindow_1",
                                    "org.kde.KMainWindow",
                                    QDBusConnection::sessionBus());
    QDBusReply<long> kontactWinId = kontactInterface.call("winId");

    KWindowSystem::forceActiveWindow (kontactWinId, 1);
}

void KOrganizerUtil::showTodo(const QString &uid)
{
    if(!QDBusConnection::sessionBus().interface()->isServiceRegistered("org.kde.kontact"))
    {
        KToolInvocation::kdeinitExecWait("kontact");
    }

    OrgKdeKorganizerKorganizerInterface interface("org.kde.korganizer",
                                                  "/Korganizer",
                                                  QDBusConnection::sessionBus());
    interface.showIncidence(uid);
    KOrganizerUtil::showMainWindow();
}

void KOrganizerUtil::showAddTodo()
{
    OrgKdeKorganizerCalendarInterface interface("org.kde.korganizer",
                                                  "/Calendar",
                                                  QDBusConnection::sessionBus());
    interface.openTodoEditor(i18n("new todo"));
    KOrganizerUtil::showMainWindow();
}
